/*
\connect mainzelliste

--
-- PostgreSQL database dump
--

-- Dumped from database version 9.5.14
-- Dumped by pg_dump version 9.5.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: patient; Type: TABLE DATA; Schema: public; Owner: mainzelliste
--

CREATE TABLE public.patient
(
  patientjpaid integer NOT NULL,
  fieldsstring text,
  inputfieldsstring text,
  istentative boolean,
  original_patientjpaid integer,
  externalid character varying(255),
  geburtsjahr character varying(4096),
  geburtsmonat character varying(4096),
  geburtstag character varying(4096),
  study character varying(255),
  CONSTRAINT patient_pkey PRIMARY KEY (patientjpaid)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.patient
  OWNER TO postgres;

-- Index: public.i_patient_original

-- DROP INDEX public.i_patient_original;

CREATE INDEX i_patient_original
ON public.patient
USING btree
(original_patientjpaid);



INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (101, '{"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"MUSTERMANN"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"MAX"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"},"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"}}', '{"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Mustermann"},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Max"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (102, '{"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"ANTONOV"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"ANTON"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69118"},"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"}}', '{"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Antonov"},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Anton"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69118"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (401, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"M"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"MAX"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"MUSTERFRAU"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1955},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"M"},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Max"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Musterfrau"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1955},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (1701, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":3},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"M"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"MUSTER"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":3},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"M"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Muster"},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', true, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (1851, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":4},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"LUISE"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1974},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"MUELLER"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69118"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":4},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Luise"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1974},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Müller"},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69118"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (2151, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"SIMONE"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"MUELLER"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1913},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":10},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Simone"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Müller"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1913},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":10},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (2651, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"SEMEON"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"SEMEONYCH"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1972},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69118"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Semeon"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Semeonych"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1972},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69118"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (2851, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"ARTEOM"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"ARTEOMOW"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Arteom"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Arteomow"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (3051, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"KIRILL"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"KIRILLOW"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Kirill"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Kirillow"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (3351, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"PEOTR"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"UEETROW"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Peotr"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Üetrow"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (3551, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"KATZE"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"KATERKOLJA"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Katze"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"KaterKolja"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1970},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', false, NULL);
INSERT INTO public.patient (patientjpaid, fieldsstring, inputfieldsstring, istentative, original_patientjpaid) VALUES (3751, '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":12},"vorname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"LAURAS"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"nachname":{"class":"de.pseudonymisierung.mainzelliste.CompoundField","value":[{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"KATZE"},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""}]},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1978},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', '{"ort":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Heidelberg"},"geburtsname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":""},"geburtstag":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":12},"vorname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Lauras"},"nachname":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"Katze"},"geburtsjahr":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":1978},"geburtsmonat":{"class":"de.pseudonymisierung.mainzelliste.IntegerField","value":2},"plz":{"class":"de.pseudonymisierung.mainzelliste.PlainTextField","value":"69117"}}', false, NULL);

ALTER TABLE public.patient OWNER TO mainzelliste
--
-- PostgreSQL database dump complete
--

*/